# The URL the site will be built for
base_url = "https://liakhovitch.github.io/public"
title = "Anton Liakhovitch: Embedded Software Engineer"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

theme = "d3c3nt"

default_language = "en"
generate_feed = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
  d3_nav = [
    { name = "HOME", path = "/" },
    { name = "GITHUB", path = "https://github.com/liakhovitch"},
    { name = "RESUME", path = "https://liakhovitch.github.io/resume/resume.pdf" },
  ]
